version: '3.8'
services:
  db:
    image: nervokid/adsbdatadb:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: replace_with_postgres_password
    volumes:
      - /home/amcarvalho/Containers/adsb/ads-b-data/.postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    network_mode: "host"
    labels:
      - homepage.group=ADSB & Applications
      - homepage.name=ADSB-Database
      - homepage.icon=https://user-images.githubusercontent.com/12117027/81372504-22c9ea00-90c0-11ea-8b58-9eaf66dd0bd1.png

  web:
    image: nervokid/adsbdatabackend:latest
    command: >
      sh -c "python main.py"
    network_mode: "host"
    environment:
      ADSB_DB_PASSWORD: replace_with_adsb_database_password
    depends_on:
      db:
        condition: service_healthy
    labels:
      - homepage.group=ADSB & Applications
      - homepage.name=ADSB-Web
      - homepage.icon=https://user-images.githubusercontent.com/12117027/81372504-22c9ea00-90c0-11ea-8b58-9eaf66dd0bd1.png
